### ISSUE TITLE
Streaming and InvalidOAuth2Credentials

### ISSUE THREAD

**Issue by dentarg** [avidw/redd#19]
I didn't want to continue off topic in #18, so therefore a new issue. Hope you are okay with me continuing asking, this might not be an particular issue with the library, just me having a rough time using it.

Anyways, you wrote in #18

> The 401 error, on the other hand, I can diagnose. The error pops up because the session expires every hour. A simple line of code can fix it. I would put that line of code directly in the stream method, but I was worried about repeat requests and possibly IP bans if the Access object wasn't properly constructed.

>     reddit.refresh_access! if reddit.access.expired?
    # ... more code ...

So I tried that... doing it like this

````ruby
reddit = Redd.it(:userless, id, secret, user_agent: USER_AGENT)
reddit.authorize!

reddit.stream "get_new", "all" do |thing|
  reddit.refresh_access! if reddit.access.expired?
  yield thing
end
````

but I keep getting 401. Was this how you thought it should be done or did you have something else in mind?

**Comment by jesalg** [comment]
I'm running into the same issue. @dentarg Were you able to figure out the correct usage of refresh_access?

**Comment by dentarg** [comment]
Nope, I haven't given this issue any more time, just ignoring the exceptions for the moment...

**Comment by jesalg** [comment]
It looks like reddit API does not allow refreshing permanent tokens. Form [their documentation](https://github.com/reddit/reddit/wiki/OAuth2):

> You may use the refresh_token to acquire a new bearer token after your current token expires. 
> The implicit grant flow does not allow permanent tokens.

I've changed my code to ask for temporary token, hopefully that should fix it.

**Comment by avidw** [comment]
**Of course**! I didn't notice that at all and was looking for problems in my code. While I fix that, temporary workaround should be:

```ruby
reddit.authorize! if reddit.access.expired?
# ... more code ...
```

I'll leave the issue open till I fix that. Thanks @jesalg!
