### ISSUE TITLE
No support for POST api/submit

### ISSUE THREAD

**Issue by sidoh** [avidw/redd#26]
Thanks for the gem! I've been enjoying using it.

Looks like there isn't support for [`POST /api/submit`](https://www.reddit.com/dev/api#POST_api_submit). I think I see where to add it, but I wanted to check that I wasn't missing something before digging in.

**Comment by avidw** [comment]
It already exists! `submit` is a method for the subreddit object.

- [Source](https://github.com/avidw/redd/blob/v0.7.8/lib/redd/objects/subreddit.rb#L20-L50)
- [Documentation (for v0.7.8)](http://www.rubydoc.info/gems/redd/0.7.8/Redd/Objects/Subreddit#submit-instance_method)

**Comment by sidoh** [comment]
Gotcha. Thanks!

Definitely poked around to find it, but I think I expected to see it somewhere else. Makes sense that it's in the subreddit object.
