### ISSUE TITLE
Rate limiting is guessing

### ISSUE THREAD

**Issue by krainboltgreene** [avidw/redd#7]
If Reddit changes their API to allow 50 requests per minute your sleep will be too slow.

Instead of having a class that tracks time (or even allowing the user to provide a time tracking object) I suggest simply reading the HTTP headers they provide and determining the availability to request then. See the [wiki details](https://github.com/reddit/reddit/wiki/API):

> X-Ratelimit-Used: Approximate number of requests used in this period
> X-Ratelimit-Remaining: Approximate number of requests left to use
> X-Ratelimit-Reset: Approximate number of seconds to end of period

**Comment by avidw** [comment]
Apologies for the late reply. I was aware of the X-Ratelimit-* headers before I began working on the project. The problem with using the headers is that requests then end up getting sent in huge bursts, leaving no requests for the rest of the interval. With this method, most users will never have to worry about the rate limit class at all and requests get sent in equal intervals, so more data is collected. This is the method PRAW uses.

On the wiki's API page, it looks like they also recommend this approach right before the section about the headers. 

> **Make no more than thirty requests per minute.** This allows some burstiness to your requests, but keep it sane. On average, we should see no more than one request every two seconds from you.

They seem to recommend using the headers as a double-check, but as far as I know, reddit doesn't block you for overflowing that once in a while, so a request every two seconds seems fine to me. I'll close the issue, but if you have other reasons to think the other approach is better, I'll be happy to re-open the issue.

**Comment by avidw** [comment]
Since I introduced a `RateLimit#burst!` method (which doesn't sleep for a certain number of requests), the rate limiting was no longer constant, so I had to figure out a way to still make rate limiting work. Then I remembered your issue and implemented the X-Ratelimit headers (see d68d96e). So thanks for your suggestion!

**Comment by krainboltgreene** [comment]
Awesome!
