### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by beatak** [avidw/redd#8]
I'm trying to test out like this:

```
r = Redd.it(:script, client_id, cient_secret, username, password)
r.authorize!
```

The call above will make a request to `/api/v1/access_token` with a request header like 

```
{
    "User-Agent": "Redd/Ruby, v0.7.3",
    "Authorization": "Basic …"
}
```

and a request body like 

```
{
    grant_type: "password",
    username: "…",
    password: "…"
}
```

and I get this:

```
redd/lib/redd/response/raise_error.rb:12:in `on_complete': {:error=>"invalid_grant"} (Redd::Error::ExpiredCode)
```

I'm stuck and I'd appreciate if you could suggest me what I'm doing wrong. Thx!

**Comment by avidw** [comment]
Hmm...I'm genuinely baffled. This error should only pop up on "web" grants. I've just tested that the login works fine on my PC for both the gem and the edge versions and your request looks [correct](https://github.com/reddit/reddit/wiki/OAuth2-Quick-Start-Example). Can you double-check some things?

- [ ] The app was created as a "script" type in [your preferences](https://www.reddit.com/prefs/apps)
- [ ] The username you're logging in with is registered as a "developer" of the app.
- [ ] Your credentials were copy-pasted correctly (I've had trouble with this twice :disappointed:)
- [ ] As a last resort, maybe try changing your user agent? `Redd.it(..., user_agent: "...")`

I hope one of these solves your issue.

**Comment by beatak** [comment]
Okay, so I figure it. I'm using `dotenv` for storing a set of password, secret and such. And my password contained `…$xxx,…` and that got interpolated.  I'm so sorry for the hassle!

One suggest I could give here is that… maybe this error, you can return `Redd::Error::InvalidCredentials` instead of `Redd::Error::ExpiredCode`?
